import { z } from "zod";

/**
 * VEGA v3.3 Loop 3: Structural Learning — Monthly Review Types
 *
 * Defines schemas for monthly structural reviews and Bet node tracking.
 * Monthly reviews synthesize 4 weeks of reflections, telemetry trends,
 * and Bar Raiser observations into structural proposals tracked as Bets.
 */

// ─── Bet Status ─────────────────────────────────────────────────────────────

export const BetStatus = z.enum([
  "pending_approval",
  "active",
  "confirmed",
  "revised",
  "abandoned",
]);
export type BetStatus = z.infer<typeof BetStatus>;

// ─── Bet Node ───────────────────────────────────────────────────────────────

export const BetSchema = z.object({
  id: z.string().uuid(),
  agent_name: z.string().min(1),
  hypothesis: z.string().min(1),
  expected_outcome: z.string().min(1),
  measurement_criteria: z.string().min(1),
  rollback_trigger: z.string().min(1),
  actual_outcome: z.string().nullable(),
  status: BetStatus,
  created_date: z.coerce.date(),
  review_date: z.coerce.date().nullable(),
  source_review_month: z.string().regex(/^\d{4}-\d{2}$/),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
});

export type Bet = z.infer<typeof BetSchema>;

export const BetInputSchema = BetSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
});

export type BetInput = z.infer<typeof BetInputSchema>;

// ─── Structural Proposal (generated by review, becomes Bet on approval) ─────

export const StructuralProposalSchema = z.object({
  agent_name: z.string().min(1),
  hypothesis: z.string().min(1),
  expected_outcome: z.string().min(1),
  measurement_criteria: z.string().min(1),
  rollback_trigger: z.string().min(1),
  rationale: z.string().min(1),
});

export type StructuralProposal = z.infer<typeof StructuralProposalSchema>;

// ─── Bet Outcome Assessment ─────────────────────────────────────────────────

export const BetOutcomeSchema = z.object({
  bet_id: z.string().uuid(),
  hypothesis: z.string(),
  expected_outcome: z.string(),
  actual_outcome: z.string(),
  new_status: BetStatus,
  evidence: z.string(),
});

export type BetOutcome = z.infer<typeof BetOutcomeSchema>;

// ─── Monthly Telemetry Trends ───────────────────────────────────────────────

export const MonthlyTrendSummarySchema = z.object({
  agent_name: z.string().min(1),
  total_actions: z.number().int().nonnegative(),
  avg_success_rate: z.number().min(0).max(1),
  avg_latency_ms: z.number().nonnegative().nullable(),
  total_cost_usd: z.number().nonnegative(),
  avg_performance_score: z.number().min(0).max(1).nullable(),
  anomaly_count: z.number().int().nonnegative(),
  trend_direction: z.enum(["improving", "stable", "declining"]),
});

export type MonthlyTrendSummary = z.infer<typeof MonthlyTrendSummarySchema>;

// ─── Monthly Review ─────────────────────────────────────────────────────────

export const MonthlyReviewSchema = z.object({
  month_start: z.coerce.date(),
  month_end: z.coerce.date(),
  generated_at: z.coerce.date(),
  agents_included: z.array(z.string().min(1)),
  agent_trends: z.array(MonthlyTrendSummarySchema),
  bar_raiser_observations: z.array(z.string()),
  bet_outcomes: z.array(BetOutcomeSchema),
  proposals: z.array(StructuralProposalSchema),
  markdown: z.string(),
});

export type MonthlyReview = z.infer<typeof MonthlyReviewSchema>;
